version: 2.0
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - checkout
      - run:
          name: Restore Packages
          command:
            dotnet restore
      - run:
          name: Build Projects
          command:
            dotnet build
      - run:
          name: Test
          command:
            dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover dotenv.net.Test/dotenv.net.Test.csproj
      - run:
          name: Install Coveralls
          command:
            dotnet tool install coveralls.net --version 1.0.0 --tool-path tools
      - run:
          name: Report Coverage
          command:
            ./tools/csmacnz.Coveralls --opencover -i ./tests/coverage.opencover.xml --repoToken $COVERALLS_REPO_TOKEN --commitId $TRAVIS_COMMIT --commitBranch $TRAVIS_BRANCH --commitAuthor "$REPO_COMMIT_AUTHOR" --commitEmail "$REPO_COMMIT_AUTHOR_EMAIL" --commitMessage "$REPO_COMMIT_MESSAGE" --jobId $TRAVIS_JOB_ID  --serviceName "travis-ci" --useRelativePaths
